# Generated by Django 3.0.8 on 2020-08-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'managed': False},
        ),
    ]
