# Generated by Django 3.0.8 on 2020-08-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0002_auto_20200812_1007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allocation',
            table='eye_allocation',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='eye_assignment',
        ),
    ]
